#!/usr/bin/env node
/**
 * One-shot script to mint the ML-DSA-87 keypair + XChaCha20 encrypt key used
 * to sign/verify team-invite tokens via @sigvault/sdk.
 *
 * Usage:
 *   npm run gen:invite-keys
 *
 * Copy the printed block into your `.env`. If left unset, team-invite
 * tokens fall back to HMAC-SHA256 (still secure for our use case; just
 * not post-quantum) — and the server logs a warning on every cold boot
 * to nudge the operator.
 */
import { generateKeypair } from "@sigvault/sdk";
import { randomBytes } from "crypto";

const kp = generateKeypair();
const chainSeed = randomBytes(32).toString("hex");

const block = `# ── Post-quantum team-invite tokens (ML-DSA-87 via @sigvault/sdk) ─────────
# Generated by \`npm run gen:invite-keys\` at ${new Date().toISOString()}
# Wire format: ~6.7 KB hex blob. URLs accept it but stay short by other means
# (e.g. shorten via a per-token redirect row if you need <2048 char links).
TEAM_INVITE_SIGNING_KEY="${Buffer.from(kp.signingKey).toString("hex")}"
TEAM_INVITE_VERIFYING_KEY="${Buffer.from(kp.verifyingKey).toString("hex")}"
TEAM_INVITE_ENCRYPT_KEY="${Buffer.from(kp.encryptKey).toString("hex")}"
TEAM_INVITE_CHAIN_SEED="${chainSeed}"
`;

console.log("✓ Generated ML-DSA-87 keypair + encrypt key + chain seed.\n");
console.log("Paste the block below into your `.env` (or your deploy's secret store):\n");
console.log(block);
console.log("Notes:");
console.log(
  "  • All three TEAM_INVITE_* vars must be set together. If any is missing,"
);
console.log("    the system falls back to HMAC-SHA256 over ENCRYPTION_KEY.");
console.log(
  "  • To rotate, re-run this script and replace the values. Existing tokens"
);
console.log(
  "    will fail to verify — invalidate active invites first (`Invitation` table)."
);
console.log(
  "  • For multi-instance deploys (Vercel, Fly, etc.), set these in the deploy's"
);
console.log(
  "    secret manager so every instance reads the SAME keys — keys generated"
);
console.log("    independently per instance won't cross-verify.");
