/**
 * Scope catalog for the OAuth 2.0 layer.
 *
 * Every endpoint under /api/v1 names the scope it requires. The consent
 * screen renders one row per scope from this catalog so the user reads
 * plain English ("read your plot listings") rather than `plots:read`.
 *
 * Adding a new scope:
 *  1. Append to SCOPES below with a description and a sensitivity tier
 *  2. Reference it in the protected route via requireScope("foo:bar")
 *  3. Add it to the OAuthApp.allowedScopes the developer registers with
 */

export type ScopeSensitivity = "read" | "write" | "send" | "admin";

export type ScopeDescriptor = {
  name: string;
  label: string;
  description: string;
  sensitivity: ScopeSensitivity;
};

export const SCOPES: ScopeDescriptor[] = [
  // Read-only
  { name: "plots:read", label: "Read your plots", description: "List and view plot listings in your org.", sensitivity: "read" },
  { name: "clients:read", label: "Read your client list", description: "List and view clients (name, phone, preferences).", sensitivity: "read" },
  { name: "visits:read", label: "Read scheduled visits", description: "List visits scheduled at any plot.", sensitivity: "read" },
  { name: "designs:read", label: "Read AI-generated designs", description: "List designs generated by the architect.", sensitivity: "read" },
  { name: "analytics:read", label: "Read analytics", description: "Aggregate counts of plots, visits, messages.", sensitivity: "read" },
  // Write
  { name: "plots:write", label: "Create + edit plots", description: "Add new plot listings or update existing ones.", sensitivity: "write" },
  { name: "clients:write", label: "Create + edit clients", description: "Invite new clients or update existing client records.", sensitivity: "write" },
  { name: "visits:write", label: "Schedule + edit visits", description: "Create or change visit appointments.", sensitivity: "write" },
  { name: "designs:write", label: "Generate AI designs", description: "Trigger architect generations (may incur AI cost).", sensitivity: "write" },
  // Send (potentially user-visible side effects)
  { name: "messages:send", label: "Send WhatsApp messages on your behalf", description: "Send messages via your org's WhatsApp integration.", sensitivity: "send" },
];

const SCOPE_BY_NAME = new Map(SCOPES.map((s) => [s.name, s]));

export function describeScopes(scopeNames: string[]): ScopeDescriptor[] {
  return scopeNames
    .map((n) => SCOPE_BY_NAME.get(n))
    .filter((s): s is ScopeDescriptor => Boolean(s));
}

export function isValidScope(name: string): boolean {
  return SCOPE_BY_NAME.has(name);
}

/** Returns true iff every requested scope is in the app's allow-list. */
export function scopesPermitted(requested: string[], allowed: string[]): boolean {
  const allowSet = new Set(allowed);
  return requested.every((s) => allowSet.has(s));
}

/** Returns true iff the granted scopes include the required one. */
export function hasScope(granted: string[], required: string): boolean {
  return granted.includes(required);
}
